name: restcountries
description: A library to load countries, states/regions, and cities.
version: '0.0.2'
homepage: https://github.com/mgufrone/restcountries
author: gufy <mgufronefendi@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  dio: ^2.1.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: 4.1.0
