name: restcountries
description: A library to load countries, states/regions, and cities (source from http://battuta.medunes.net/).
version: '0.0.3'
homepage: https://github.com/mgufrone/restcountries
author: gufy <mgufronefendi@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  dio: ^3.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: 4.1.0
